const products = [
  {
    id: '1',
    name: 'Máy Ảnh Mini 512G CCD',
    price: 299000,
    discount: 25,
    image: 'https://picsum.photos/200',
  },
  {
    id: '2',
    name: 'Quạt Mini Cầm Tay N68',
    price: 27900,
    discount: 13,
    image: 'https://picsum.photos/200',
  },
  {
    id: '3',
    name: 'Đèn Ngủ LED Cảm Ứng',
    price: 49000,
    discount: 10,
    image: 'https://picsum.photos/200',
  },
  {
    id: '4',
    name: 'Bình Nước Thể Thao 1L',
    price: 65000,
    discount: 15,
    image: 'https://picsum.photos/200',
  },
  {
    id: '5',
    name: 'Tai Nghe Bluetooth TWS',
    price: 159000,
    discount: 20,
    image: 'https://picsum.photos/200',
  },
  {
    id: '6',
    name: 'Sạc Dự Phòng 10000mAh',
    price: 199000,
    discount: 18,
    image: 'https://picsum.photos/200',
  },
  {
    id: '7',
    name: 'Bàn Phím Cơ Mini',
    price: 299000,
    discount: 22,
    image: 'https://picsum.photos/200',
  },
  {
    id: '8',
    name: 'Chuột Không Dây Silent',
    price: 89000,
    discount: 12,
    image: 'https://picsum.photos/200',
  },
  {
    id: '9',
    name: 'Đồng Hồ Thông Minh S8',
    price: 349000,
    discount: 30,
    image: 'https://picsum.photos/200',
  },
  {
    id: '10',
    name: 'Loa Bluetooth Mini',
    price: 129000,
    discount: 17,
    image: 'https://picsum.photos/200',
  },
  {
    id: '11',
    name: 'Quạt Để Bàn USB',
    price: 59000,
    discount: 14,
    image: 'https://picsum.photos/200',
  },
  {
    id: '12',
    name: 'Cáp Sạc Nhanh Type-C',
    price: 39000,
    discount: 8,
    image: 'https://picsum.photos/200',
  },
  {
    id: '13',
    name: 'Ổ Cắm Điện Thông Minh',
    price: 99000,
    discount: 16,
    image: 'https://picsum.photos/200',
  },
  {
    id: '14',
    name: 'Balo Laptop Chống Nước',
    price: 249000,
    discount: 21,
    image: 'https://picsum.photos/200',
  },
  {
    id: '15',
    name: 'Đèn Pin Mini Siêu Sáng',
    price: 39000,
    discount: 11,
    image: 'https://picsum.photos/200',
  },
  {
    id: '16',
    name: 'Bộ Dụng Cụ Sửa Chữa Đa Năng',
    price: 79000,
    discount: 19,
    image: 'https://picsum.photos/200',
  },
  {
    id: '17',
    name: 'Kính Mát Chống Tia UV',
    price: 59000,
    discount: 14,
    image: 'https://picsum.photos/200',
  },
  {
    id: '18',
    name: 'Bình Giữ Nhiệt 500ml',
    price: 99000,
    discount: 18,
    image: 'https://picsum.photos/200',
  },
  {
    id: '19',
    name: 'Đồng Hồ Báo Thức Điện Tử',
    price: 69000,
    discount: 12,
    image: 'https://picsum.photos/200',
  },
  {
    id: '20',
    name: 'Túi Đựng Mỹ Phẩm Du Lịch',
    price: 49000,
    discount: 15,
    image: 'https://picsum.photos/200',
  },
  {
    id: '21',
    name: 'Bộ Sạc 3 Cổng USB',
    price: 59000,
    discount: 17,
    image: 'https://picsum.photos/200',
  },
  {
    id: '22',
    name: 'Bàn Chải Đánh Răng Điện',
    price: 129000,
    discount: 20,
    image: 'https://picsum.photos/200',
  },
  {
    id: '23',
    name: 'Gối Cổ Du Lịch',
    price: 39000,
    discount: 10,
    image: 'https://picsum.photos/200',
  },
  {
    id: '24',
    name: 'Bộ Dây Đèn LED Trang Trí',
    price: 59000,
    discount: 13,
    image: 'https://picsum.photos/200',
  },
  {
    id: '25',
    name: 'Bộ Lọc Nước Vòi Sen',
    price: 79000,
    discount: 16,
    image: 'https://picsum.photos/200',
  },
  {
    id: '26',
    name: 'Bộ Đồ Chơi Xếp Hình Mini',
    price: 49000,
    discount: 9,
    image: 'https://picsum.photos/200',
  },
  {
    id: '27',
    name: 'Bộ Dụng Cụ Làm Bếp Đa Năng',
    price: 99000,
    discount: 18,
    image: 'https://picsum.photos/200',
  },
  {
    id: '28',
    name: 'Bộ Sạc Không Dây',
    price: 159000,
    discount: 22,
    image: 'https://picsum.photos/200',
  },
  {
    id: '29',
    name: 'Bộ Phát Wifi Di Động',
    price: 299000,
    discount: 25,
    image: 'https://picsum.photos/200',
  },
  {
    id: '30',
    name: 'Bộ Lọc Không Khí Mini',
    price: 199000,
    discount: 19,
    image: 'https://picsum.photos/200',
  },
  {
    id: '31',
    name: 'Bộ Đèn LED Gắn Xe Đạp',
    price: 69000,
    discount: 14,
    image: 'https://picsum.photos/200',
  },
  {
    id: '32',
    name: 'Bộ Đồ Nghề Sửa Xe Mini',
    price: 89000,
    discount: 15,
    image: 'https://picsum.photos/200',
  },
  {
    id: '33',
    name: 'Bộ đồ ngủ mini',
    price: 100000,
    discount: 20,
    image: 'https://picsum.photos/200',
  },
];

export default products;